version: '3'
services:
  db:
    image: postgres:10-alpine
    ports:
      - ${DB_PORT:-5435}:5432
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DB:-gscatalog}
      POSTGRES_USER: ${DB_POSTGRES_USER:-gscatalog}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-gscatalog}
  geoserver-1:
    image: savi/geoserver:0.0.12-2.16.0
    ports:
      - 8081:8080
    environment:
      GEOSERVER_ADMIN_PASSWORD: admin
      JDBCCONFIG_ENABLED: "true"
      JDBCCONFIG_INITDB: "false"
      JDBCCONFIG_IMPORT: "false"
      JDBCCONFIG_JDBC_URL: jdbc:postgresql:\/\/db:5432\/gscatalog
      JDBCCONFIG_USERNAME: gscatalog
      JDBCCONFIG_PASSWORD: gscatalog
    depends_on:
      - db
  geoserver-2:
    image: savi/geoserver:0.0.12-2.16.0
    ports:
      - 8082:8080
    environment:
      GEOSERVER_ADMIN_PASSWORD: admin
      JDBCCONFIG_ENABLED: "true"
      JDBCCONFIG_INITDB: "false"
      JDBCCONFIG_IMPORT: "false"
      JDBCCONFIG_JDBC_URL: jdbc:postgresql:\/\/db:5432\/gscatalog
      JDBCCONFIG_USERNAME: gscatalog
      JDBCCONFIG_PASSWORD: gscatalog
    depends_on:
      - db
